name: chusen_kun
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  cloud_firestore: ^3.2.1
  firebase_messaging: ^12.0.0
  flutter_native_splash: ^2.2.5
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/party_bingo_taikai_man.png
    - assets/shingou_machi.png
    - assets/pose_lose_boy.png
    - assets/pose_win_boy.png
    - assets/text_kansya.png
flutter_native_splash:
  color: '#add8e6'
  image: 'assets/splash.png'
  color_dark: '#262626'
  image_dark: 'assets/splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#add8e6'
    image: 'assets/splash.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/splash.png'